export const concerts = [
  {
    id: "1",
    festivalName: "Creamfields",
    bandName: "Prodigy",
    date: "2005/11/12",
    place: "Costanera Sur",
    location: "Av. España 2230, CABA, Argentina",
    company: "Ticketmaster",
    price: 65,
    variant: "green",
  },
  {
    id: "2",
    festivalName: "Personal Fest 05",
    bandName: "Duran Duran",
    date: "2005/12/03",
    place: "Dique 1, Puerto Madero",
    location: "Juana Manso & Boulevard Rosario Vera Peñaloza, CABA, Argentina",
    company: "Ticketmaster",
    price: 70,
    variant: "blue",
  },
  {
    id: "3",
    festivalName: "The Dark Side of the Moon",
    bandName: "Roger Waters",
    date: "2007/03/16",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 120,
    variant: "orange",
  },
  {
    id: "4",
    festivalName: "Me Verás Volver",
    bandName: "Soda Stereo",
    date: "2007/12/21",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 90,
    variant: "yellow",
  },
  {
    id: "5",
    festivalName: "The Red Carpet Massacre Tour",
    bandName: "Duran Duran",
    date: "2008/11/07",
    place: "Club GEBA",
    location: "Av. Coronel Marcelino E. Freyre 3831, CABA, Argentina",
    company: "TopShow",
    price: 0,
    variant: "red",
  },
  {
    id: "6",
    festivalName: "Quilmes Rock 2009",
    bandName: "Kiss",
    date: "2009/04/05",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 90,
    variant: "skyblue",
  },
  {
    id: "7",
    festivalName: "Pepsi Music 2009",
    bandName: "Faith No More - Die Toten Hosen",
    date: "2009/11/01",
    place: "Estadio Club Ciudad de Buenos Aires",
    location: "Av. del Libertador 7501, CABA, Argentina",
    company: "Ticketek",
    price: 130,
    variant: "darkblue",
  },
  {
    id: "8",
    festivalName: "Personal Fest 2009",
    bandName: "Depeche Mode",
    date: "2009/10/17",
    place: "Estadio Club Ciudad de Buenos Aires",
    location: "Av. del Libertador 7501, CABA, Argentina",
    company: "Ticketek",
    price: 280,
    variant: "lightblue",
  },
  {
    id: "9",
    festivalName: "Liebe Ist Für Alle Da Tour 2010",
    bandName: "Rammstein",
    date: "2009/11/27",
    place: "Estadio Racing Club",
    location: "Mozart y Corbatta, Avellaneda, Argentina",
    company: "Ticketek",
    price: 200,
    variant: "amber",
  },
  {
    id: "10",
    festivalName: "Black Ice Tour",
    bandName: "AC/DC",
    date: "2009/12/04",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 220,
    variant: "orange",
  },
  {
    id: "11",
    festivalName: "Pepsi Music 2010",
    bandName: "Rage Against The Machine - QOTSA",
    date: "2010/10/13",
    place: "Costanera Sur",
    location: "Av. España 2230, CABA, Argentina",
    company: "TuEntrada",
    price: 200,
    variant: "darkred",
  },
  {
    id: "12",
    festivalName: "Black Clouds & Silver Touring",
    bandName: "Dream Theater",
    date: "2010/10/13",
    place: "Luna Park",
    location: "Av. Madero 420, CABA, Argentina",
    company: "TicketPortal",
    price: 100,
    variant: "slate",
  },
  {
    id: "13",
    festivalName: "Reunion Tour",
    bandName: "System of a Down",
    date: "2011/10/05",
    place: "Club GEBA",
    location: "Av. Coronel Marcelino E. Freyre 3831, CABA, Argentina",
    company: "TicketPortal",
    price: 220,
    variant: "red",
  },
  {
    id: "14",
    festivalName: "The Wall Live Tour",
    bandName: "Roger Waters",
    date: "2012/03/20",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "LivePass",
    price: 250,
    variant: "darkred",
  },
  {
    id: "15",
    festivalName: "Personal Fest 2012",
    bandName: "Kings of Leon",
    date: "2012/12/01",
    place: "Club GEBA",
    location: "Av. Figueroa Alcorta 5575, CABA, Argentina",
    company: "TopShow",
    price: 350,
    variant: "pink",
  },
  {
    id: "16",
    festivalName: "Pepsi Music 2013",
    bandName: "QOTSA - Pearl Jam - The Black Keys",
    date: "2013/04/02",
    place: "Costanera Sur",
    location: "Av. España 2230, CABA, Argentina",
    company: "Livepass",
    price: 600,
    variant: "darkblue",
  },
  {
    id: "17",
    festivalName: "Coexist Tour",
    bandName: "The XX",
    date: "2013/10/15",
    place: "Mandarine Park",
    location: "Acceso Punta Carrasco, CABA, Argentina",
    company: "Ticketek",
    price: 250,
    variant: "black",
  },
  {
    id: "18",
    festivalName: "Lollapalooza 2014",
    bandName: "Arcade Fire - Phoenix - NIN - RHCP - Soundgarden",
    date: "2014/04/01",
    place: "Hipódromo de San Isidro",
    location: "Av. Márquez 800, San Isidro, Argentina",
    company: "TopShow",
    price: 700,
    variant: "orange",
    small: true,
  },
  {
    id: "19",
    festivalName: "Frente a Frente",
    bandName: "Carajo",
    date: "2014/06/14",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 100,
    variant: "black",
  },
  {
    id: "20",
    festivalName: "Bs As Summer Break",
    bandName: "Incubus",
    date: "2014/12/14",
    place: "Complejo al Río",
    location: "Laprida y Bartolome Cruz, Vicente Lopez, Argentina",
    company: "Ticketek",
    price: 400,
    variant: "lightorange",
  },
  {
    id: "21",
    festivalName: "Sol Invictus Tour",
    bandName: "Faith No More",
    date: "2015/09/20",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 356,
    variant: "black",
  },
  {
    id: "22",
    festivalName: "Sol Invictus Tour",
    bandName: "System of a Down - Deftones",
    date: "2015/09/30",
    place: "Club GEBA",
    location: "Av. Figueroa Alcorta 5575, CABA, Argentina",
    company: "TopShow",
    price: 650,
    variant: "red",
  },
  {
    id: "23",
    festivalName: "The Astonishing",
    bandName: "Dream Theater",
    date: "2016/06/28",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 800,
    variant: "amber",
  },
  {
    id: "24",
    festivalName: "Festival BUE",
    bandName: "Iggy Pop",
    date: "2016/10/14",
    place: "Tecnópolis",
    location: "J.B. de la Salle 4365, Villa Martelli, Argentina",
    company: "Ticketek",
    price: 1265,
    variant: "skyblue",
  },
  {
    id: "25",
    festivalName: "What Went Down",
    bandName: "Foals",
    date: "2016/10/22",
    place: "Groove",
    location: "Av. Santa Fe 4389, CABA, Argentina",
    company: "Ticketek",
    price: 440,
    variant: "teal",
  },
  {
    id: "26",
    festivalName: "Strange Little Birds Tour",
    bandName: "Garbage",
    date: "2016/12/13",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 400,
    variant: "pink",
  },
  {
    id: "27",
    festivalName: "Global Spirit Tour",
    bandName: "Depeche Mode",
    date: "2018/03/25",
    place: "Estadio Único de La Plata",
    location: "Av. 25, B1900 La Plata, Argentina",
    company: "Ticketek",
    price: 1250,
    variant: "red",
  },
  {
    id: "28",
    festivalName: "Gore Tour",
    bandName: "Deftones",
    date: "2018/06/01",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 1250,
    variant: "black",
  },
  {
    id: "29",
    festivalName: "The Amulet Tour",
    bandName: "Circa Survive",
    date: "2018/09/08",
    place: "Uniclub",
    location: "Guardia Vieja 3360, CABA, Argentina",
    company: "Ticketek",
    price: 1345,
    variant: "orange",
  },
];
