export const concerts = [
  {
    id: "1",
    festivalName: "Creamfields",
    bandName: "The Prodigy",
    date: "2005/11/12",
    place: "Costanera Sur",
    location: "Av. España 2230, CABA, Argentina",
    company: "Ticketmaster",
    price: 65,
    variant: "green",
    description:
      "La edición de 2005 del festival de música electrónica Creamfields Buenos Aires tuvo lugar en la Costanera Sur y contó con más de 60.000 asistentes. El festival incluyó 10 espacios de recreación y más de 100 artistas, entre ellos: The Prodigy, Audio Bullys, Infusión, Zuker XP, Paul Oakenfold, Danny Tenaglia, Danny Howells, Hernán Cattaneo, 2 Many DJs, David Guetta.",
    songs: [
      "Intro",
      "Wake The Fuck Up",
      "Their Law",
      "Hotride",
      "Breathe",
      "Spitfire",
      "Back 2 Skool",
      "Firestarter",
      "Action Radar",
      "Warning",
      "Climbatize",
      "Voodoo People",
      "Poison",
      "Method Beats",
      "Smack My Bitch Up",
      "Out Of Space",
    ],
    playlist: "1f4z64mJB63m8lZWj0a5Za",
  },
  {
    id: "2",
    festivalName: "Personal Fest 05",
    bandName: "Duran Duran",
    date: "2005/12/03",
    place: "Dique 1, Puerto Madero",
    location: "Juana Manso & Boulevard Rosario Vera Peñaloza, CABA, Argentina",
    company: "Ticketmaster",
    price: 70,
    variant: "blue",
    description:
      "The event was named after its main sponsor Personal and is televised nationally in Argentina. Duran Duran headlined the 2005 weekend event on the Saturday evening. The weekend also included performances by the US pop-punk band Good Charlotte, Simple Minds, Macy Grey and Erykah Badu.",
    songs: [
      "(Reach Up for the) Sunrise",
      "Hungry Like the Wolf",
      "Planet Earth",
      "Union of the Snake",
      "I Don't Want Your Love",
      "Come Undone",
      "Taste the Summer",
      "The Reflex",
      "Chains",
      "Ordinary World",
      "Notorious",
      "I Want to Take You Higher (Sly & the Family Stone cover)",
      "Girls on Film",
      "Save a Prayer",
      "Nice",
      "Rio",
      "A View to a Kill",
      "Instant Karma! (John Lennon cover)",
      "The Wild Boys",
    ],
    playlist: "3Xn0qkzyCjjWJrT4cJCs2V",
  },
  {
    id: "3",
    festivalName: "The Dark Side of the Moon",
    bandName: "Roger Waters",
    date: "2007/03/16",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 120,
    variant: "orange",
    description:
      "The 50,000 attendees who packed River Plate Stadium on Saturday to see Roger Waters admired, almost hypnotically, the art of the Pink Floyd leader in a concert that lasted almost three hours. Far from the hysterical crowd that deafens at every sigh of a Latin metrosexual heartthrob, entire families and young people who inherited the melancholy of the 70s gathered to not miss one of the figures who revolutionized world music.",
    songs: [
      "In the Flesh (Pink Floyd song)",
      "Mother (Pink Floyd song)",
      "Set the Controls for the Heart of the Sun (Pink Floyd song)",
      "Shine On You Crazy Diamond (Parts I-V) (Pink Floyd song)",
      "Have a Cigar (Pink Floyd song)",
      "Wish You Were Here (Pink Floyd song)",
      "Southampton Dock (Pink Floyd song)",
      "The Fletcher Memorial Home (Pink Floyd song)",
      "Perfect Sense (Parts 1 and 2)",
      "Leaving Beirut",
      "Sheep",
      "Speak to Me (Pink Floyd song)",
      "Breathe (In the Air) (Pink Floyd song)",
      "On the Run (Pink Floyd song)",
      "Time (Pink Floyd song)",
      "Breathe (Reprise) (Pink Floyd song)",
      "The Great Gig in the Sky (Pink Floyd song)",
      "Money (Pink Floyd song)",
      "Us and Them (Pink Floyd song)",
      "Any Colour You Like (Pink Floyd song)",
      "Brain Damage (Pink Floyd song)",
      "Eclipse",
      "The Happiest Days of Our Lives (Pink Floyd song)",
      "Another Brick in the Wall, Part 2 (Pink Floyd song)",
      "Vera (Pink Floyd song)",
      "Bring the Boys Back Home (Pink Floyd song)",
      "Comfortably Numb",
    ],
  },
  {
    id: "4",
    festivalName: "Me Verás Volver",
    bandName: "Soda Stereo",
    date: "2007/12/21",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 90,
    variant: "yellow",
    description:
      '"Me Verás Volver" was a series of concerts that marked the return of the Argentine rock band Soda Stereo after 10 years since their farewell tour. It visited America between October and December 2007. Due to the pressure from their fans, additional dates had to be added beyond the scheduled ones, concluding the concert series on December 21, 2007. By the end, the band managed to attract a total of over 1,000,000 people, averaging more than 50,000 spectators per concert.',
    songs: [
      "Juego de seducción",
      "Si no fuera por...",
      "Imágenes retro",
      "Texturas",
      "Hombre al agua",
      "En la ciudad de la furia",
      "Picnic en el 4°B",
      "Lo que sangra (La cúpula)",
      "Zoom",
      "Cuando pase el temblor",
      "Final caja negra",
      "Corazón delator",
      "Signos",
      "Sobredosis de TV",
      "Danza rota",
      "Persiana americana",
      "Fue",
      "En remolinos",
      "Primavera 0",
      "No existes",
      "Sueles dejarme solo",
      "(En) el séptimo día",
      "Un millón de años luz",
      "De música ligera",
      "Encore: Disco eterno",
      "Encore: Cae el sol",
      "Encore: Prófugos",
      "Encore 2: Terapia de amor intensiva",
      "Encore 2: Nada personal",
      "Encore 2: Te hacen falta vitaminas",
    ],
  },
  {
    id: "5",
    festivalName: "The Red Carpet Massacre Tour",
    bandName: "Duran Duran",
    date: "2008/11/07",
    place: "Club GEBA",
    location: "Av. Coronel Marcelino E. Freyre 3831, CABA, Argentina",
    company: "TopShow",
    price: 0,
    variant: "red",
    songs: [
      "The Valley",
      "Planet Earth",
      "Hungry Like the Wolf",
      "Nite-Runner",
      "Notorious",
      "I Don't Want Your Love",
      "Save a Prayer",
      "Red Carpet Massacre",
      "A View to a Kill",
      "Falling Down",
      "The Reflex",
      "Come Undone",
      "The Chauffeur",
      "Skin Divers",
      "Is There Something I Should Know?",
      "Serious",
      "Nice",
      "White Lines (Don't Don't Do It) (Grandmaster Melle Mel cover)",
      "(Reach Up for the) Sunrise",
      "The Wild Boys",
      "Encore: Girls on Film",
      "Encore: Ordinary World",
      "Encore: Rio",
    ],
  },
  {
    id: "6",
    festivalName: "Quilmes Rock 2009",
    bandName: "Kiss",
    date: "2009/04/05",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 90,
    variant: "skyblue",
    songs: [
      "Deuce",
      "Strutter",
      "Got to Choose",
      "Hotter Than Hell",
      "Nothin' to Lose",
      "C'mon and Love Me",
      "Parasite",
      "She",
      "Guitar Solo",
      "Watchin' You",
      "100,000 Years",
      "Drum Solo",
      "Cold Gin",
      "Let Me Go, Rock 'n' Roll",
      "Black Diamond",
      "Rock and Roll All Nite",
      "Encore: Shout It Out Loud",
      "Encore: Lick It Up",
      "Encore: Bass Solo",
      "Encore: I Love It Loud",
      "Encore: I Was Made for Lovin' You",
      "Encore: Love Gun",
      "Encore: Detroit Rock City",
    ],
  },
  {
    id: "7",
    festivalName: "Personal Fest 2009",
    bandName: "Depeche Mode",
    date: "2009/10/17",
    place: "Estadio Club Ciudad de Buenos Aires",
    location: "Av. del Libertador 7501, CABA, Argentina",
    company: "Ticketek",
    price: 280,
    variant: "lightblue",
    songs: [
      "In Chains",
      "Wrong",
      "Hole To Feed",
      "Walking In My Shoes",
      "It's No Good",
      "A Question Of Time",
      "Precious",
      "Fly On The Windscreen",
      "Jezebel",
      "Home",
      "Miles Away / The Truth Is",
      "Policy Of Truth",
      "In Your Room",
      "I Feel You",
      "Enjoy The Silence",
      "Never Let Me Down Again",
      "Encore: Somebody",
      "Encore: Stripped",
      "Encore: Behind The Wheel",
      "Encore 2: Personal Jesus",
    ],
  },
  {
    id: "8",
    festivalName: "Pepsi Music 2009",
    bandName: "Faith No More - Die Toten Hosen",
    date: "2009/11/01",
    place: "Estadio Club Ciudad de Buenos Aires",
    location: "Av. del Libertador 7501, CABA, Argentina",
    company: "Ticketek",
    price: 130,
    variant: "darkblue",
    songs: [
      "Reunited",
      "From Out of Nowhere",
      "Land of Sunshine",
      "Caffeine",
      "Evidence",
      "Surprise! You're Dead!",
      "Last Cup of Sorrow",
      "Ricochet",
      "Easy",
      "Epic",
      "Midlife Crisis",
      "I Started a Joke",
      "The Gentle Art of Making Enemies",
      "King for a Day",
      "A Small Victory",
      "Ashes to Ashes",
      "We Care a Lot",
      "Encore: Collision",
      "Encore: Digging the Grave",
    ],
  },
  {
    id: "9",
    festivalName: "Liebe Ist Für Alle Da Tour 2010",
    bandName: "Rammstein",
    date: "2009/11/27",
    place: "Estadio Racing Club",
    location: "Mozart y Corbatta, Avellaneda, Argentina",
    company: "Ticketek",
    price: 200,
    variant: "amber",
    songs: [
      "Rammlied",
      "B********",
      "Waidmanns Heil",
      "Keine Lust",
      "Weisses Fleisch",
      "Feuer frei!",
      "Wiener Blut",
      "Frühling in Paris",
      "Mein Teil",
      "Du riechst so gut",
      "Benzin",
      "Links 2 3 4",
      "Du hast",
      "Pussy",
      "Encore: Sonne",
      "Encore: Haifisch",
      "Encore: Ich will",
      "Encore 2: Te quiero puta!",
    ],
  },
  {
    id: "10",
    festivalName: "Black Ice Tour",
    bandName: "AC/DC",
    date: "2009/12/04",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "Ticketek",
    price: 220,
    variant: "orange",
    songs: [
      "Rock 'n' Roll Train",
      "Hell Ain't a Bad Place to Be",
      "Back in Black",
      "Big Jack",
      "Dirty Deeds Done Dirt Cheap",
      "Shot Down in Flames",
      "Thunderstruck",
      "Black Ice",
      "The Jack",
      "Hells Bells",
      "Shoot to Thrill",
      "War Machine",
      "Dog Eat Dog",
      "You Shook Me All Night Long",
      "T.N.T.",
      "Whole Lotta Rosie",
      "Let There Be Rock",
      "Encore: Highway to Hell",
      "Encore: For Those About to Rock (We Salute You)",
    ],
  },
  {
    id: "11",
    festivalName: "Pepsi Music 2010",
    bandName: "Rage Against The Machine - QOTSA",
    date: "2010/10/13",
    place: "Costanera Sur",
    location: "Av. España 2230, CABA, Argentina",
    company: "TuEntrada",
    price: 200,
    variant: "darkred",
    songs: [
      "Testify",
      "Bombtrack",
      "People of the Sun",
      "Know Your Enemy",
      "Bulls on Parade",
      "Township Rebellion",
      "Guerrilla Radio",
      "Bullet in the Head",
      "Calm Like a Bomb",
      "Sleep Now in the Fire",
      "Wake Up",
      "Encore: L'Internationale",
      "Encore: Freedom",
      "Encore: Killing in the Name",
    ],
  },
  {
    id: "12",
    festivalName: "Black Clouds & Silver Touring",
    bandName: "Dream Theater",
    date: "2010/10/13",
    place: "Luna Park",
    location: "Av. Madero 420, CABA, Argentina",
    company: "TicketPortal",
    price: 100,
    variant: "slate",
    songs: [
      "A Nightmare to Remember",
      "A Rite of Passage",
      "Hollow Years",
      "Keyboard Solo",
      "Prophets of War",
      "Act II: Scene Seven: I. The Dance of Eternity",
      "Act II: Scene Seven: II. One Last Time",
      "Act II: Scene Eight: The Spirit Carries On",
      "In the Name of God",
      "Encore: The Count of Tuscany",
    ],
  },
  {
    id: "13",
    festivalName: "Reunion Tour",
    bandName: "System of a Down",
    date: "2011/10/05",
    place: "Club GEBA",
    location: "Av. Coronel Marcelino E. Freyre 3831, CABA, Argentina",
    company: "TicketPortal",
    price: 220,
    variant: "red",
    songs: [
      "Prison Song",
      "Soldier Side - Intro",
      "B.Y.O.B.",
      "Revenga",
      "Needles",
      "Deer Dance",
      "Radio/Video",
      "Hypnotize",
      "Question!",
      "Suggestions",
      "Psycho",
      "Chop Suey!",
      "Lonely Day",
      "Bounce",
      "ATWA",
      "Kill Rock 'n Roll",
      "Lost in Hollywood",
      "Forest",
      "Science",
      "Mind",
      "Innervision",
      "Holy Mountains",
      "Aerials",
      "Vicinity of Obscenity",
      "Tentative",
      "Cigaro",
      "Suite-Pee",
      "War?",
      "Toxicity",
      "Sugar",
    ],
  },
  {
    id: "14",
    festivalName: "The Wall Live Tour",
    bandName: "Roger Waters",
    date: "2012/03/20",
    place: "Estadio River Plate",
    location: "Av. Pres. Figueroa Alcorta 7597, CABA, Argentina",
    company: "LivePass",
    price: 250,
    variant: "darkred",
    songs: [
      "In the Flesh?",
      "The Thin Ice",
      "Another Brick in the Wall, Part 1",
      "The Happiest Days of Our Lives",
      "Another Brick in the Wall, Part 2",
      "The Ballad of Jean Charles de Menezes ('Another Brick in the Wall Part 2' reprise)",
      "Mother",
      "Goodbye Blue Sky",
      "Empty Spaces",
      "What Shall We Do Now?",
      "Young Lust",
      "One of My Turns",
      "Don't Leave Me Now",
      "Another Brick in the Wall, Part 3",
      "The Last Few Bricks",
      "Goodbye Cruel World",
      "Hey You",
      "Is There Anybody Out There?",
      "Nobody Home",
      "Vera",
      "Bring the Boys Back Home",
      "Comfortably Numb",
      "The Show Must Go On",
      "In the Flesh",
      "Run Like Hell",
      "Waiting for the Worms",
      "Stop",
      "The Trial",
      "Outside the Wall",
    ],
  },
  {
    id: "15",
    festivalName: "Personal Fest 2012",
    bandName: "Kings of Leon",
    date: "2012/12/01",
    place: "Club GEBA",
    location: "Av. Figueroa Alcorta 5575, CABA, Argentina",
    company: "TopShow",
    price: 350,
    variant: "pink",
    songs: [
      "Molly's Chambers",
      "Taper Jean Girl",
      "Four Kicks",
      "The Immortals",
      "Fans",
      "Back Down South",
      "Crawl",
      "No Money",
      "Radioactive",
      "Notion",
      "Be Somebody",
      "Closer",
      "Pyro",
      "On Call",
      "Knocked Up",
      "Sex on Fire",
      "Encore: The Bucket",
      "Manhattan",
      "Use Somebody",
      "Black Thumbnail",
    ],
  },
  {
    id: "16",
    festivalName: "Pepsi Music 2013",
    bandName: "QOTSA - Pearl Jam - The Black Keys",
    date: "2013/04/02",
    place: "Costanera Sur",
    location: "Av. España 2230, CABA, Argentina",
    company: "Livepass",
    price: 600,
    variant: "darkblue",
    songs: [
      "QOTSA - The Lost Art of Keeping a Secret",
      "QOTSA - No One Knows",
      "QOTSA - First It Giveth",
      "QOTSA - Sick, Sick, Sick",
      "QOTSA - Burn the Witch (Intro jam)",
      "QOTSA - Monsters in the Parasol",
      "QOTSA - Misfit Love",
      "QOTSA - Hangin' Tree",
      "QOTSA - Make It Wit Chu",
      "QOTSA - My God Is the Sun",
      "QOTSA - Little Sister",
      "QOTSA - A Song for the Deaf",
      "QOTSA - Go With the Flow",
      "QOTSA - A Song for the Dead",
      "Pearl Jam - Release",
      "Pearl Jam - Even Flow",
      "Pearl Jam - Lukin",
      "Pearl Jam - Corduroy",
      "Pearl Jam - In Hiding",
      "Pearl Jam - Save You",
      "Pearl Jam - Deep",
      "Pearl Jam - Jeremy",
      "Pearl Jam - Wishlist",
      "Pearl Jam - Hail, Hail",
      "Pearl Jam - Given to Fly",
      "Pearl Jam - I Got Id",
      "Pearl Jam - Daughter",
      "Pearl Jam - It's Okay (Dead Moon cover) (Spanish version titled 'Está bien', sung entirely in Spanish)",
      "Pearl Jam - Got Some",
      "Pearl Jam - Better Man (with 'Save It for Later' tag)",
      "Pearl Jam - Elderly Woman Behind the Counter in a Small Town",
      "Pearl Jam - Rearviewmirror",
      "Pearl Jam - Encore: Do the Evolution",
      "Pearl Jam - Animal",
      "Pearl Jam - Just Breathe",
      "Pearl Jam - Black",
      "Pearl Jam - I Believe in Miracles (Ramones cover)",
      "Pearl Jam - Alive",
      "Pearl Jam - Rockin' in the Free World (Neil Young cover)",
      "Pearl Jam - Yellow Ledbetter",
      "The Black Keys - Howlin' for You",
      "The Black Keys - Next Girl",
      "The Black Keys - Run Right Back",
      "The Black Keys - Same Old Thing",
      "The Black Keys - Dead and Gone",
      "The Black Keys - Gold on the Ceiling",
      "The Black Keys - Thickfreakness",
      "The Black Keys - Girl Is on My Mind",
      "The Black Keys - Your Touch",
      "The Black Keys - Little Black Submarines",
      "The Black Keys - Money Maker",
      "The Black Keys - Strange Times",
      "The Black Keys - Sinister Kid",
      "The Black Keys - Nova Baby",
      "The Black Keys - Ten Cent Pistol",
      "The Black Keys - She's Long Gone",
      "The Black Keys - Tighten Up",
      "The Black Keys - Lonely Boy",
      "The Black Keys - I Got Mine",
    ],
  },
  {
    id: "17",
    festivalName: "Coexist Tour",
    bandName: "The XX",
    date: "2013/10/15",
    place: "Mandarine Park",
    location: "Acceso Punta Carrasco, CABA, Argentina",
    company: "Ticketek",
    price: 250,
    variant: "black",
    songs: [
      "Try",
      "Crystalised",
      "Reunion",
      "Far Nearer (Jamie xx song)",
      "Sunset",
      "Missing",
      "Fiction",
      "Night Time",
      "Swept Away",
      "Shelter",
      "VCR",
      "Islands",
      "Chained",
      "Infinity",
      "Encore: Intro",
      "Encore: Angels",
    ],
  },
  {
    id: "18",
    festivalName: "Lollapalooza 2014",
    bandName: "Arcade Fire - Phoenix - NIN - RHCP - Soundgarden",
    date: "2014/04/01",
    place: "Hipódromo de San Isidro",
    location: "Av. Márquez 800, San Isidro, Argentina",
    company: "TopShow",
    price: 700,
    variant: "orange",
    small: true,
    songs: [
      "Normal Person",
      "Rebellion (Lies)",
      "Reflektor",
      "Flashbulb Eyes",
      "Neighborhood #3",
      "The Suburbs",
      "The Suburbs",
      "Ready to Start",
      "Neighborhood #1",
      "No Cars Go",
      "We Exist",
      "Afterlife",
      "It's Never Over",
      "Sprawl II",
      "Keep the Car Running",
      "Here Comes the Night Time",
      "Wake Up",
    ],
  },
  {
    id: "19",
    festivalName: "Frente a Frente",
    bandName: "Carajo",
    date: "2014/06/14",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 100,
    variant: "black",
    songs: [
      "Trágico mundo caído",
      "Drama",
      "La venganza de los perdedores",
      "Shock",
      "A espaldas del bien",
      "Tracción a sangre",
      "Para vos",
      "Sobrevivir",
      "Andante",
      "Promesas",
      "Histeria, TV, canción de moda",
      "Chico granada",
      "Ironía",
      "Pura vida",
      "El error",
      "El llanto espiritual",
      "Acorazados",
      "Virus anti-amor",
      "Zion",
      "Alma y fuego",
      "Fantasmas",
      "Atrapasueños",
      "Humildad",
      "Triste",
      "Luna herida",
      "Ácido",
      "Libres",
      "Joder",
      "Salvaje",
      "Sacate la mierda",
    ],
  },
  {
    id: "20",
    festivalName: "Bs As Summer Break",
    bandName: "Incubus",
    date: "2014/12/14",
    place: "Complejo al Río",
    location: "Laprida y Bartolome Cruz, Vicente Lopez, Argentina",
    company: "Ticketek",
    price: 400,
    variant: "lightorange",
    songs: [
      "Quicksand",
      "A Kiss to Send Us Off",
      "Megalomaniac",
      "Nice to Know You",
      "Adolescents",
      "Made for TV Movie (with a snippet of 'Hello' by Lionel Richie)",
      "Circles",
      "Talk Shows on Mute",
      "Anna Molly",
      "In the Company of Wolves",
      "Punch Drunk",
      "Drive",
      "Dig",
      "Are You In? (with a snippet of 'Riders on the Storm')",
      "Wish You Were Here",
      "Sick Sad Little World",
      "Pardon Me",
    ],
  },
  {
    id: "21",
    festivalName: "Sol Invictus Tour",
    bandName: "Faith No More",
    date: "2015/09/20",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 356,
    variant: "black",
    songs: [
      "Motherfucker",
      "Be Aggressive",
      "Caffeine",
      "Everything's Ruined",
      "Evidence",
      "Epic",
      "Black Friday",
      "Midlife Crisis",
      "Last Cup of Sorrow",
      "The Gentle Art of Making Enemies",
      "Easy",
      "Separation Anxiety",
      "Matador",
      "Ashes to Ashes",
      "Superhero",
      "Encore: Cone of Shame",
      "Encore: Digging the Grave",
      "Encore: Just a Man",
      "Encore 2: We Care a Lot",
    ],
  },
  {
    id: "22",
    festivalName: "2015 Latin American Tour",
    bandName: "System of a Down - Deftones",
    date: "2015/09/30",
    place: "Club GEBA",
    location: "Av. Figueroa Alcorta 5575, CABA, Argentina",
    company: "TopShow",
    price: 650,
    variant: "red",
    songs: [
      "I-E-A-I-A-I-O",
      "Suite-Pee",
      "Attack",
      "Prison Song",
      "Know",
      "Aerials",
      "Soldier Side - Intro",
      "B.Y.O.B.",
      "Soil",
      "Darts",
      "Radio/Video",
      "Hypnotize",
      "Temper",
      "ATWA",
      "CUBErt",
      "Needles",
      "Deer Dance",
      "Bounce",
      "Suggestions",
      "Psycho",
      "Chop Suey!",
      "Lonely Day",
      "Question!",
      "Lost in Hollywood",
      "Vicinity of Obscenity",
      "Forest",
      "Spiders",
      "Cigaro",
      "Toxicity",
      "Sugar",
    ],
  },
  {
    id: "23",
    festivalName: "The Astonishing",
    bandName: "Dream Theater",
    date: "2016/06/28",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 800,
    variant: "amber",
    songs: [
      "Dystopian Overture",
      "The Gift of Music",
      "The Answer",
      "A Better Life",
      "Lord Nafaryus",
      "A Savior in the Square",
      "When Your Time Has Come",
      "Act of Faythe",
      "Three Days",
      "Brother, Can You Hear Me?",
      "A Life Left Behind",
      "Ravenskill",
      "Chosen",
      "A Tempting Offer",
      "The X Aspect",
      "A New Beginning",
      "The Road to Revolution",
      "2285 Entr'acte",
      "Moment of Betrayal",
      "Heaven's Cove",
      "Begin Again",
      "The Path That Divides",
      "The Walking Shadow",
      "My Last Farewell",
      "Losing Faythe",
      "Whispers on the Wind",
      "Hymn of a Thousand Voices",
      "Our New World",
      "Encore: Astonishing",
    ],
  },
  {
    id: "24",
    festivalName: "Festival BUE",
    bandName: "Iggy Pop",
    date: "2016/10/14",
    place: "Tecnópolis",
    location: "J.B. de la Salle 4365, Villa Martelli, Argentina",
    company: "Ticketek",
    price: 1265,
    variant: "skyblue",
    songs: [
      "I Wanna Be Your Dog",
      "The Passenger",
      "Lust for Life",
      "Five Foot One",
      "Sixteen",
      "Skull Ring",
      "1969",
      "Sister Midnight",
      "Real Wild Child",
      "Nightclubbing",
      "Some Weird Sin",
      "Mass Production",
      "Encore: Repo Man",
      "Encore: Search and Destroy",
      "Encore: Gardenia",
      "Encore: Down on the Street",
      "Encore: Loose",
      "Encore: Raw Power",
      "Encore: No Fun",
      "Encore 2: Candy",
    ],
  },
  {
    id: "25",
    festivalName: "What Went Down",
    bandName: "Foals",
    date: "2016/10/22",
    place: "Groove",
    location: "Av. Santa Fe 4389, CABA, Argentina",
    company: "Ticketek",
    price: 440,
    variant: "teal",
    songs: [
      "Prelude",
      "Snake Oil",
      "Olympic Airways",
      "My Number",
      "Hummer",
      "Blue Blood",
      "Give It All",
      "Mountain at My Gates",
      "Providence",
      "Spanish Sahara",
      "Red Socks Pugie",
      "Late Night",
      "A Knife in the Ocean",
      "Inhaler",
      "Encore: What Went Down",
      "Encore: Cassius",
      "Encore: Two Steps, Twice",
    ],
  },
  {
    id: "26",
    festivalName: "Strange Little Birds Tour",
    bandName: "Garbage",
    date: "2016/12/13",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 400,
    variant: "pink",
    songs: [
      "Supervixen",
      "I Think I'm Paranoid",
      "Stupid Girl",
      "Automatic Systematic Habit",
      "Blood for Poppies",
      "The Trick Is to Keep Breathing",
      "Sex Is Not the Enemy",
      "Blackout",
      "Magnetized",
      "Special",
      "#1 Crush",
      "Even Though Our Love Is Doomed",
      "Why Do You Love Me",
      "Night Drive Loneliness",
      "Bleed Like Me",
      "Shut Your Mouth",
      "Vow (with 'Don't Hurt Yourself' snippet by Beyoncé)",
      "Only Happy When It Rains",
      "Push It",
      "Encore: Queer",
      "Encore: Empty",
      "Encore: Cherry Lips (Go Baby Go!)",
    ],
  },
  {
    id: "27",
    festivalName: "Global Spirit Tour",
    bandName: "Depeche Mode",
    date: "2018/03/25",
    place: "Estadio Único de La Plata",
    location: "Av. 25, B1900 La Plata, Argentina",
    company: "Ticketek",
    price: 1250,
    variant: "red",
    songs: [
      "Going Backwards",
      "It's No Good",
      "Barrel of a Gun",
      "A Pain That I'm Used To",
      "Useless",
      "Precious",
      "World in My Eyes",
      "Cover Me",
      "Insight",
      "Home",
      "In Your Room",
      "Where's the Revolution",
      "Everything Counts",
      "Stripped",
      "Enjoy the Silence",
      "Never Let Me Down Again",
      "Encore: Strangelove",
      "Encore: Walking in My Shoes",
      "Encore: A Question of Time",
      "Encore: Personal Jesus",
    ],
  },
  {
    id: "28",
    festivalName: "Gore Tour",
    bandName: "Deftones",
    date: "2018/06/01",
    place: "Luna Park",
    location: "Av. Madero 412, CABA, Argentina",
    company: "TicketPortal",
    price: 1250,
    variant: "black",
    description:
      "The American alternative metal band returns to Argentina to play on June 1st at the legendary Luna Park, presenting their latest studio album: Gore. This will be their first solo show in the country, following their visit in 2015 alongside System of a Down. The California quintet, led by vocalist/guitarist Chino Moreno, arrives with the current lineup, consisting of guitarist Stephen Carpenter, keyboardist/sampler Frank Delgado, drummer Abe Cunningham, and bassist Sergio Vega.",
    songs: [
      "Headup",
      "Be Quiet and Drive (Far Away)",
      "My Own Summer (Shove It)",
      "Around the Fur",
      "Swerve City",
      "Elite",
      "Digital Bath",
      "Knife Prty",
      "Rosemary",
      "What Happened to You?",
      "Kimdracula",
      "Hole in the Earth",
      "Change (In the House of Flies)",
      "Diamond Eyes",
      "You've Seen the Butcher",
      "Rocket Skates",
      "Encore: Minerva",
      "Encore: Nosebleed",
      "Encore: 7 Words",
    ],
    playlist: "5y6Pp6utLxqW1LeH7ImmoR",
  },
  {
    id: "29",
    festivalName: "The Amulet Tour",
    bandName: "Circa Survive",
    date: "2018/09/08",
    place: "Uniclub",
    location: "Guardia Vieja 3360, CABA, Argentina",
    company: "Ticketek",
    price: 1345,
    variant: "orange",
    songs: [
      "Rites of Investiture",
      "The Difference Between Medicine and Poison Is in the Dose",
      "Wish Resign",
      "Tunnel Vision",
      "Child of the Desert",
      "Get Out",
      "Stay",
      "The Great Golden Baby",
      "Lustration",
      "At Night It Gets Worse",
      "Living Together",
      "Act Appalled",
      "Dyed in the Wool",
      "I Felt Free",
      "Descensus",
    ],
  },
];
